Repository BSPQ24-25/BSPQ25-E2, pull requests merged in 2025-05, with the labels that each got.

#136 Fix controller uppercase
  src/main/java/com/deusto/deuspotify/Controllers/AuthController.java
  src/main/java/com/deusto/deuspotify/Controllers/I18nController.java
  src/main/java/com/deusto/deuspotify/Controllers/PlaylistController.java
  src/main/java/com/deusto/deuspotify/Controllers/ProfileController.java
  src/main/java/com/deusto/deuspotify/Controllers/SongController.java
  src/test/java/com/deusto/deuspotify/DeuspotifyApplicationTests.java
Labels: enhancement

#138 137 implement docker
  .github/workflows/docker-publish.yml
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  Dockerfile
  docker-compose.yml
  mvnw
  mvnw.cmd
  src/main/java/com/deusto/deuspotify/DataInitializer.java
  src/main/resources/application-docker.properties
  src/main/resources/application.properties
Labels: task

#156 See other playlist
  src/main/resources/static/index.html
  src/main/resources/static/view_all_playlist.html
Labels: user story
